# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_countinue',
            field=models.TextField(blank=True, null=True),
        ),
    ]
